.TH "bws_snapshot_filter" "3" "2015-09-03" "Bowsprit" "Bowsprit\ documentation"
.SH NAME
.PP
bws_snapshot_filter \[en] Filtering snapshots
.SH SYNOPSIS
.PP
\f[B]#include <bowsprit.h>\f[]
.PP
void
.PD 0
.P
.PD
\f[B]bws_snapshot_filter_by_type_name\f[](struct bws_snapshot
*\f[I]src\f[],
.PD 0
.P
.PD
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ const
char *\f[I]type_name\f[],
.PD 0
.P
.PD
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ struct
bws_snapshot *\f[I]dest\f[]);
.SH DESCRIPTION
.PP
The \f[B]bws_snapshot_filter\f[] family of functions filters the
contents of a source snapshot, writing the results into a separate
destination snapshot.
(The filtering is not done in\-place, so you must not provide the same
snapshot for both the \f[I]src\f[] and \f[I]dest\f[] parameters.)
.PP
\f[B]bws_snapshot_filter_by_type_name\f[]() only keeps the values that
belong to a measurement with the given type name.
